### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by Diandres** [OfficeDev/microsoft-teams-build2017-weather#2]
Broken link https://github.com/billbliss/microsoft-teams-build2017-weather.git

> Type the following in your project directory to merge this project with yours, grab the OpenWeatherMap Font project, and to tweak your project.json file to support jQuery:

> git remote add weather https://github.com/billbliss/microsoft-teams-build2017-weather.git_

@billbliss

**Comment by clearab** [comment]
fixed, thanks!
